"""Short-first generation from a topic, source docs, niche, and meme plan.

This module is intentionally separate from the long-video pipeline. It writes
only under a short variant directory and produces the same ``ShortScript`` shape
the existing shorts voiceover/storyboard/render code already understands.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML is optional for built-in defaults.
    yaml = None

from ..config import Config, load_config
from ..understanding.llm_provider import LLMProvider, get_llm_provider
from .beat_mode import build_beat_mode_plan
from .component_plan import build_component_plan
from .meme_assets import resolve_meme_assets
from .meme_copy import generate_meme_copy
from .meme_provider import select_meme_asset_provider, validate_imgflip_credentials
from .models import ShortMode, ShortScene, ShortScript
from .niche import get_editing_config, get_script_context, get_voice_config, load_niche
from .research_aggregator import ResearchAggregator
from .scene_recipe import SceneRecipeInput, plan_scene_recipes
from .script_beats import build_script_beats


@dataclass
class ResearchNote:
    """A normalized research/source note for short script prompting."""

    source: str
    title: str
    snippet: str
    url: str = ""
    score: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ResearchBundle:
    """Research context passed into the short-first LLM prompt."""

    topic: str
    niche: str
    notes: list[ResearchNote]

    def to_prompt_text(self) -> str:
        lines = [f"Topic: {self.topic}", f"Niche: {self.niche}"]
        for index, note in enumerate(self.notes, start=1):
            source = f"{note.source}: {note.title}".strip(": ")
            lines.append(f"{index}. [{source}] {note.snippet}")
            if note.url:
                lines.append(f"   URL: {note.url}")
        return "\n".join(lines)


@dataclass
class NicheProfile:
    """Guidance for shaping a short for a content niche."""

    name: str
    tone: str
    hook_style: str
    pacing: str
    caption_style: str
    cta_style: str
    meme_density: str = "medium"
    target_duration_seconds: int = 50


@dataclass
class MemeMoment:
    """A structured meme/editing moment, never raw JSX."""

    time_start: float
    time_end: float
    meme_type: str
    caption: str
    visual_style: str
    reason: str = ""


@dataclass
class ShortFirstResult:
    """Files generated by short-first script creation."""

    success: bool
    variant: str
    research_path: Path
    short_script_path: Path
    short_script_md_path: Path
    meme_plan_path: Path
    script_beats_path: Path | None = None
    component_plan_path: Path | None = None
    beat_mode_plan_path: Path | None = None
    character_plan_path: Path | None = None
    scene_recipe_plan_path: Path | None = None
    error: str | None = None


BUILTIN_NICHES: dict[str, NicheProfile] = {
    "default": NicheProfile(
        name="default",
        tone="clear, energetic, and curious",
        hook_style="start with a surprising claim or tension",
        pacing="fast but understandable, 6 to 8 beats",
        caption_style="short punchy captions with one idea at a time",
        cta_style="soft follow or full breakdown CTA",
        meme_density="medium",
        target_duration_seconds=50,
    ),
    "tech": NicheProfile(
        name="tech",
        tone="smart, crisp, slightly playful",
        hook_style="open with a misconception, failure, or surprising capability",
        pacing="dense, 6 to 9 beats, no filler",
        caption_style="clean technical captions with bold contrast words",
        cta_style="invite viewers to follow for the full breakdown",
        meme_density="medium",
        target_duration_seconds=50,
    ),
    "comedy": NicheProfile(
        name="comedy",
        tone="playful, punchy, absurd but readable",
        hook_style="open with a relatable pain or ridiculous contrast",
        pacing="very fast, frequent reversals",
        caption_style="meme-forward captions with reaction labels",
        cta_style="quick joke CTA",
        meme_density="high",
        target_duration_seconds=50,
    ),
    "finance": NicheProfile(
        name="finance",
        tone="sharp, practical, skeptical",
        hook_style="open with a number, risk, or hidden tradeoff",
        pacing="fast but credibility-first",
        caption_style="number-led captions with simple explanations",
        cta_style="ask viewers to follow for deeper analysis",
        meme_density="low",
        target_duration_seconds=50,
    ),
}


SHORT_FIRST_SYSTEM_PROMPT = """You create clean, engaging 45-55 second vertical video scripts.

Return strict JSON only. Do not generate JSX or code.

The JSON shape:
{
  "title": "Short title",
  "hook": "Opening hook or cliffhanger question",
  "narration": "Full spoken narration, no markdown",
  "beats": [
    {"caption": "caption words", "start": 0, "end": 8, "visual": "visual plan"}
  ],
  "cta": "CTA narration",
  "meme_moments": [
    {
      "time_start": 8,
      "time_end": 11,
      "meme_type": "reaction_label",
      "caption": "confidently wrong",
      "visual_style": "zoom shake red stamp",
      "reason": "why this moment works"
    }
  ]
}
"""


class ShortFirstGenerator:
    """Generate short-first scripts, research bundles, and meme plans."""

    def __init__(
        self,
        config: Config | None = None,
        llm: LLMProvider | None = None,
        niches_dir: Path | None = None,
        research_aggregator_factory: Callable[..., ResearchAggregator] | None = None,
    ):
        self.config = config or load_config()
        self.llm = llm or get_llm_provider(self.config)
        self.niches_dir = niches_dir or Path("niches")
        self.research_aggregator_factory = research_aggregator_factory or ResearchAggregator

    def load_niche_profile(self, niche: str | None) -> NicheProfile:
        """Load a niche profile from YAML or built-in defaults."""

        requested = (niche or "default").strip().lower()
        yaml_profile = load_niche("general" if requested == "default" else requested)
        script = yaml_profile.get("script", {}) or {}
        captions = yaml_profile.get("captions", {}) or {}
        editing = get_editing_config(yaml_profile)
        if yaml_profile:
            return NicheProfile(
                name=str(yaml_profile.get("name") or requested),
                tone=str(script.get("tone") or BUILTIN_NICHES["default"].tone),
                hook_style=_first_hook_template(script) or BUILTIN_NICHES["default"].hook_style,
                pacing=str(script.get("pacing") or BUILTIN_NICHES["default"].pacing),
                caption_style=str(captions.get("position") or BUILTIN_NICHES["default"].caption_style),
                cta_style=", ".join(script.get("cta_variants", [])[:2]) or BUILTIN_NICHES["default"].cta_style,
                meme_density="high" if editing.get("style") == "meme_heavy" else "medium",
                target_duration_seconds=50,
            )
        return BUILTIN_NICHES.get(requested, BUILTIN_NICHES["default"])

    def build_research_bundle(
        self,
        topic: str,
        source_paths: list[Path] | None = None,
        research: bool = False,
        niche: str = "default",
        logger: Callable[[str], None] | None = None,
    ) -> ResearchBundle:
        """Create a normalized research bundle from local sources and topic."""

        notes: list[ResearchNote] = []
        for source_path in source_paths or []:
            text = source_path.read_text(encoding="utf-8")
            notes.append(
                ResearchNote(
                    source="source",
                    title=source_path.name,
                    snippet=_compact(text, limit=1200),
                    score=1.0,
                    metadata={"path": str(source_path)},
                )
            )

        emit = logger or (lambda _message: None)
        if research:
            emit("Research: querying Reddit, RSS, DuckDuckGo, webpages, and pytrends")
            try:
                profile = load_niche("general" if niche == "default" else niche)
                aggregator = self.research_aggregator_factory(
                    topic,
                    niche=niche,
                    discovery=profile.get("discovery", {}) or {},
                    logger=emit,
                )
                live_items = aggregator.gather(limit=10)
                notes.extend(
                    ResearchNote(
                        source=item.source,
                        title=item.title,
                        snippet=item.snippet,
                        url=item.url,
                        score=item.score,
                        metadata=item.metadata,
                    )
                    for item in live_items
                )
                emit(f"Research: aggregated {len(live_items)} live item(s)")
            except Exception as exc:
                emit(f"Research: live aggregation failed; using fallback ({exc})")

        if not notes:
            notes.append(
                ResearchNote(
                    source="topic",
                    title=topic,
                    snippet=f"Create a short explainer about: {topic}",
                    score=0.25,
                )
            )

        return ResearchBundle(topic=topic, niche=niche, notes=notes)

    def generate(
        self,
        project_id: str,
        project_dir: Path,
        topic: str,
        source_paths: list[Path] | None = None,
        niche: str = "default",
        variant: str = "default",
        duration: int | None = None,
        research: bool = False,
        mock: bool = False,
        logger: Callable[[str], None] | None = None,
    ) -> ShortFirstResult:
        """Generate short-first files under ``project_dir/short/<variant>``."""

        emit = logger or (lambda _message: None)
        target_duration = _clamp_duration(duration or 50)
        variant_dir = project_dir / "short" / variant
        research_dir = variant_dir / "research"
        beats_dir = variant_dir / "beats"
        meme_dir = variant_dir / "memes"
        component_dir = variant_dir / "components"
        plans_dir = variant_dir / "plans"
        research_path = research_dir / "research.json"
        script_beats_path = beats_dir / "script_beats.json"
        short_script_path = variant_dir / "short_script.json"
        short_script_md_path = variant_dir / "short_script.md"
        meme_plan_path = meme_dir / "meme_plan.json"
        component_plan_path = component_dir / "component_plan.json"
        beat_mode_plan_path = plans_dir / "beat_mode_plan.json"
        character_plan_path = plans_dir / "character_plan.json"
        scene_recipe_plan_path = plans_dir / "scene_recipe_plan.json"

        profile = self.load_niche_profile(niche)
        yaml_profile = load_niche("general" if profile.name == "default" else profile.name)
        emit("Building short-first research bundle")
        bundle = self.build_research_bundle(
            topic=topic,
            source_paths=source_paths,
            research=research,
            niche=profile.name,
            logger=emit,
        )
        synctoon_manifest = _load_synctoon_manifest(self.config.character.asset_source)
        synctoon_options = _synctoon_visual_options(synctoon_manifest)

        emit("Writing short script, beats, and meme plan")
        prompt = self._build_prompt(bundle, profile, target_duration, synctoon_options)
        raw = _mock_short_payload(topic, target_duration) if mock else self.llm.generate_json(prompt, SHORT_FIRST_SYSTEM_PROMPT)

        narration = str(raw.get("narration") or "").strip()
        if not narration:
            narration = f"{topic}. Here is the fast version. Patterns create predictions, but context decides whether they work."

        title = str(raw.get("title") or topic).strip()
        hook = str(raw.get("hook") or raw.get("hook_question") or f"Why does {topic} matter?").strip()
        cta = str(raw.get("cta") or "Follow for the full breakdown.").strip()
        word_budget = max(1, int(target_duration * 2.2) - len(cta.split()))
        if len(narration.split()) > word_budget and not mock:
            emit(
                f"Narration exceeds {target_duration}s budget: "
                f"{len(narration.split()) + len(cta.split())} words; requesting shorter copy"
            )
            try:
                shortened = self.llm.generate_json(
                    (
                        f"Shorten this narration to at most {word_budget} words. "
                        "Keep sourced facts, the hook, and conclusion. Return JSON with only a narration field.\n\n"
                        f"{narration}"
                    ),
                    "You edit vertical-video narration for strict duration. Return strict JSON only.",
                )
                candidate = str(shortened.get("narration") or "").strip()
                if candidate:
                    narration = candidate
            except Exception as exc:
                emit(f"Narration shortening pass failed; applying hard word budget ({exc})")
        narration = _enforce_narration_budget(narration, cta, target_duration)
        emit(
            f"Narration budget: {len(narration.split()) + len(cta.split())} words "
            f"for {target_duration}s"
        )
        beats = list(raw.get("beats") or [])
        script_beats = build_script_beats(narration, profile.name)
        for beat, raw_beat in zip(script_beats, beats, strict=False):
            visual_hint = str(raw_beat.get("visual", "")).strip()
            if visual_hint:
                beat["visual_description"] = visual_hint
            if raw_beat.get("caption"):
                beat["caption_text"] = str(raw_beat.get("caption", "")).strip()
        visual_direction = _normalize_visual_direction(
            raw.get("visual_direction") or raw.get("visual_style") or {},
            script_beats,
            synctoon_manifest,
            profile.name,
        )
        raw_memes = _build_meme_items(raw, script_beats, yaml_profile)
        meme_provider = select_meme_asset_provider(mock=mock)
        emit(f"Meme plan: raw={len(raw_memes)} provider={meme_provider}")
        meme_items = generate_meme_copy(
            raw_memes,
            narration,
            [],
            provider=meme_provider,
            llm=self.llm,
            logger=lambda message: emit(f"Meme: {message}"),
        )
        if meme_provider == "imgflip":
            meme_validation = validate_imgflip_credentials(live=False)
            emit(f"Meme: Imgflip validation -> {'ok' if meme_validation.ok else 'not ready'}: {meme_validation.message}")
        meme_items = resolve_meme_assets(
            meme_items,
            meme_dir / "assets",
            public_root=project_dir,
            provider=meme_provider,
            logger=lambda message: emit(f"Meme: {message}"),
        )
        emit(f"Meme plan: finalized={len(meme_items)}")
        meme_slots = _meme_slots(len(script_beats), len(meme_items))
        beat_mode_plan = build_beat_mode_plan(script_beats, meme_slots=meme_slots)
        beat_modes_by_id = {str(item["id"]): str(item.get("mode", "")) for item in beat_mode_plan}
        character_plan = {
            "character_id": "character_1",
            "video_background": visual_direction["video_background"],
            "beat_modes": beat_modes_by_id,
            "beats": [
                {
                    "id": beat["beat_id"],
                    "mode": beat_modes_by_id.get(str(beat["beat_id"]), ""),
                    "body_type": visual_direction["beats_by_id"].get(beat["beat_id"], {}).get("body_type", "body1"),
                    "emotion": visual_direction["beats_by_id"].get(beat["beat_id"], {}).get("emotion", "content"),
                    "head": visual_direction["beats_by_id"].get(beat["beat_id"], {}).get("head", "M"),
                    "gesture": visual_direction["beats_by_id"].get(beat["beat_id"], {}).get("gesture", ""),
                    "reason": visual_direction["beats_by_id"].get(beat["beat_id"], {}).get("reason", ""),
                }
                for beat in script_beats
            ],
        }
        component_plan = build_component_plan(
            script_beats,
            meme_items,
            duration=target_duration,
            niche=profile.name,
            mode_plan=beat_mode_plan,
        )
        emit("Planning mixed scenes and recurring character beats")
        recipe_inputs = _build_scene_recipe_inputs(
            script_beats=script_beats,
            component_plan=component_plan,
            beat_mode_plan=beat_mode_plan,
            project_id=project_id,
            topic=topic,
            niche=profile.name,
            visual_direction=visual_direction,
        )
        scene_recipes = plan_scene_recipes(
            recipe_inputs,
            seed=f"{project_id}:{variant}:{topic}:{profile.name}",
        )

        short_script = ShortScript(
            source_project=project_id,
            title=title,
            condensed_narration=narration,
            hook_question=hook,
            scenes=[
                ShortScene(
                    source_scene_id=f"short_first_beat_{index + 1}",
                    duration_seconds=float(_beat_duration(beat, target_duration, len(beats), index)),
                )
                for index, beat in enumerate(beats or [{"caption": narration}])
            ],
            cta_text=cta,
            cta_narration=cta,
            total_duration_seconds=float(target_duration),
            mode=ShortMode.HOOK,
        )

        research_dir.mkdir(parents=True, exist_ok=True)
        beats_dir.mkdir(parents=True, exist_ok=True)
        meme_dir.mkdir(parents=True, exist_ok=True)
        component_dir.mkdir(parents=True, exist_ok=True)
        plans_dir.mkdir(parents=True, exist_ok=True)
        variant_dir.mkdir(parents=True, exist_ok=True)

        emit(f"Saving research bundle -> {research_path}")
        research_path.write_text(
            json.dumps(_bundle_to_dict(bundle), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        emit(f"Saving short script -> {short_script_path}")
        short_script_path.write_text(
            short_script.model_dump_json(indent=2),
            encoding="utf-8",
        )
        emit(f"Saving markdown script -> {short_script_md_path}")
        short_script_md_path.write_text(
            _format_short_script_markdown(short_script, beats, profile),
            encoding="utf-8",
        )
        emit(f"Saving script beats -> {script_beats_path}")
        script_beats_path.write_text(
            json.dumps({"beats": script_beats}, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        emit(f"Saving meme plan -> {meme_plan_path}")
        meme_plan_path.write_text(
            json.dumps(
                {
                    "project": project_id,
                    "variant": variant,
                    "niche": profile.name,
                    "provider": "imgflip",
                    "env": {
                        "template_id": "MCP_MEME_TEMPLATE_ID",
                        "username": "IMGFLIP_USERNAME",
                        "password": "IMGFLIP_PASSWORD",
                    },
                    "moments": meme_items,
                },
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )
        emit(f"Saving component plan -> {component_plan_path}")
        component_plan_path.write_text(
            json.dumps(component_plan, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        emit(f"Saving beat mode plan -> {beat_mode_plan_path}")
        beat_mode_plan_path.write_text(
            json.dumps({"beats": beat_mode_plan}, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        emit(f"Saving character plan -> {character_plan_path}")
        character_plan_path.write_text(
            json.dumps(character_plan, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        emit(f"Saving scene recipe plan -> {scene_recipe_plan_path}")
        scene_recipe_plan_path.write_text(
            json.dumps(
                {
                    "project_id": project_id,
                    "variant": variant,
                    "recipes": [recipe.model_dump() for recipe in scene_recipes],
                },
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )
        emit("Short-first generation complete")

        return ShortFirstResult(
            success=True,
            variant=variant,
            research_path=research_path,
            short_script_path=short_script_path,
            short_script_md_path=short_script_md_path,
            script_beats_path=script_beats_path,
            meme_plan_path=meme_plan_path,
            component_plan_path=component_plan_path,
            beat_mode_plan_path=beat_mode_plan_path,
            character_plan_path=character_plan_path,
            scene_recipe_plan_path=scene_recipe_plan_path,
        )

    def _build_prompt(
        self,
        bundle: ResearchBundle,
        profile: NicheProfile,
        duration: int,
        synctoon_options: dict[str, Any],
    ) -> str:
        body_types = ", ".join(synctoon_options.get("body_types", [])[:32])
        body_aliases = ", ".join(
            f"{alias}->{target}" for alias, target in synctoon_options.get("body_aliases", {}).items()
        )
        heads = ", ".join(synctoon_options.get("heads", []))
        backgrounds = ", ".join(
            f"{item['name']}={item['path']}" for item in synctoon_options.get("backgrounds", [])
        )
        return f"""Create a {duration}-second vertical short script.

Research:
{bundle.to_prompt_text()}

Niche guidance:
{get_script_context(load_niche("general" if profile.name == "default" else profile.name))}

Voice guidance:
{json.dumps(get_voice_config(load_niche("general" if profile.name == "default" else profile.name), provider="edge"), ensure_ascii=False)}

Requirements:
- Spoken narration should fit {duration} seconds.
- Use 8 to 12 clean attention-span beats when possible.
- Generate meme moments as structured timing instructions, not code.
- Prefer component-friendly visual descriptions: attention maps, token grids, flow diagrams, masked grids, progress bars, meme cards.
- Keep claims grounded in the research/source notes.

Synctoon visual options:
- Choose ONE video background for the whole short and keep it consistent.
- Pick body types and gestures per beat from the provided options.
- Body types: {body_types}
- Semantic body aliases: {body_aliases}
- Head variants: {heads}
- Background images: {backgrounds}

Return an extra top-level "visual_direction" object:
{{
  "video_background": {{"name": "...", "path": "...", "reason": "..."}},
  "beats": [
    {{"beat_id": "beat_001", "body_type": "body6", "head": "M", "emotion": "content", "gesture": "explain", "reason": "..."}}
  ]
}}

Keep the background fixed across all beats. Make body choice vary beat-to-beat when it improves humor or emphasis.
"""


def _compact(text: str, limit: int) -> str:
    compacted = re.sub(r"\s+", " ", text).strip()
    return compacted[:limit]


def _load_synctoon_manifest(asset_source: str) -> dict[str, Any]:
    root = Path(asset_source)
    if root.is_file():
        manifest_path = root
    else:
        manifest_path = root / "character-manifest.json"
        if not manifest_path.exists():
            for candidate in (
                root / "character_1" / "character-manifest.json",
                root / "characters" / "synctoon" / "character_1" / "character-manifest.json",
                root / "remotion" / "public" / "characters" / "synctoon" / "character_1" / "character-manifest.json",
            ):
                if candidate.exists():
                    manifest_path = candidate
                    break
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def _synctoon_visual_options(manifest: dict[str, Any]) -> dict[str, Any]:
    assets = manifest.get("assets", {})
    body_assets = assets.get("body", {})
    head_assets = assets.get("head", {})
    backgrounds = assets.get("background", {})
    body_types = sorted(
        {
            _manifest_asset_stem(str(item.get("path", "")))
            for item in body_assets.values()
            if _manifest_asset_stem(str(item.get("path", "")))
        }
    )
    heads = sorted(
        {
            _manifest_asset_stem(str(item.get("path", "")))
            for item in head_assets.values()
            if _manifest_asset_stem(str(item.get("path", "")))
        }
    )
    background_options = sorted(
        [
            {
                "name": str(name),
                "path": str(item.get("path", "")),
            }
            for name, item in backgrounds.items()
            if str(item.get("path", "")).strip()
        ],
        key=lambda item: item["name"],
    )
    body_aliases = {
        str(name): _manifest_asset_stem(str(item.get("path", "")))
        for name, item in body_assets.items()
        if ":" in str(name) and _manifest_asset_stem(str(item.get("path", "")))
    }
    return {
        "body_types": body_types,
        "body_aliases": body_aliases,
        "heads": heads,
        "backgrounds": background_options,
    }


def _manifest_asset_stem(path_text: str) -> str:
    return Path(path_text).stem.strip()


def _resolve_background_name(
    requested: Any,
    manifest: dict[str, Any],
    fallback_background: str,
) -> dict[str, str]:
    backgrounds = manifest.get("assets", {}).get("background", {})
    if isinstance(requested, dict):
        name = str(requested.get("name") or "").strip()
        path = str(requested.get("path") or "").strip()
        if name and path:
            return {"name": name, "path": path}
    if isinstance(requested, str) and requested in backgrounds:
        item = backgrounds[requested]
        path = str(item.get("path", "")).strip()
        if path:
            return {"name": requested, "path": path}
    if fallback_background in backgrounds:
        item = backgrounds[fallback_background]
        path = str(item.get("path", "")).strip()
        if path:
            return {"name": fallback_background, "path": path}
    for name, item in backgrounds.items():
        path = str(item.get("path", "")).strip()
        if path:
            return {"name": str(name), "path": path}
    return {"name": fallback_background, "path": ""}


def _resolve_body_type(
    requested: str,
    manifest: dict[str, Any],
    fallback_body: str,
) -> str:
    body_assets = manifest.get("assets", {}).get("body", {})
    if requested in body_assets:
        path = str(body_assets[requested].get("path", "")).strip()
        stem = Path(path).stem
        return stem or requested
    if fallback_body in body_assets:
        path = str(body_assets[fallback_body].get("path", "")).strip()
        stem = Path(path).stem
        return stem or fallback_body
    return fallback_body


def _normalize_visual_direction(
    raw_direction: dict[str, Any],
    script_beats: list[dict[str, Any]],
    manifest: dict[str, Any],
    niche: str,
) -> dict[str, Any]:
    if not isinstance(raw_direction, dict):
        raw_direction = {}
    options = _synctoon_visual_options(manifest)
    available_bodies = options["body_types"] or ["body1"]
    available_heads = options["heads"] or ["M"]
    available_backgrounds = options["backgrounds"] or [
        {"name": "plain", "path": "characters/synctoon/character_1/background/plain/plain.png"}
    ]
    fallback_background_name = str(manifest.get("fallbacks", {}).get("background", available_backgrounds[0]["name"]))
    selected_background = _resolve_background_name(
        raw_direction.get("video_background"),
        manifest,
        fallback_background_name,
    )
    if not selected_background["path"]:
        selected_background = available_backgrounds[0]

    beats: list[dict[str, Any]] = []
    raw_beats = raw_direction.get("beats") or []
    for index, beat in enumerate(script_beats):
        beat_id = str(beat.get("beat_id", f"beat_{index + 1:03d}"))
        raw_beat = next(
            (item for item in raw_beats if str(item.get("beat_id", "")) == beat_id),
            raw_beats[index] if index < len(raw_beats) else {},
        )
        body_type = _resolve_body_type(
            str(raw_beat.get("body_type") or available_bodies[index % len(available_bodies)]),
            manifest,
            available_bodies[index % len(available_bodies)],
        )
        head = "M"
        gesture = str(raw_beat.get("gesture") or raw_beat.get("emotion") or beat.get("caption_text") or beat.get("visual_description") or "explain").strip()
        if not gesture:
            gesture = "explain"
        beats.append(
            {
                "beat_id": beat_id,
                "body_type": body_type,
                "head": head,
                "emotion": str(raw_beat.get("emotion") or ("content" if niche != "comedy" else "happy")),
                "gesture": gesture,
                "reason": str(raw_beat.get("reason") or ""),
                "background_image": selected_background["path"],
            }
        )

    return {
        "video_background": selected_background,
        "beats_by_id": {item["beat_id"]: item for item in beats},
        "beats": beats,
    }


def _meme_slots(beat_count: int, meme_count: int) -> set[int]:
    """Spread meme beats without placing them consecutively."""

    if beat_count < 3 or meme_count <= 0:
        return set()
    available = list(range(1, beat_count, 2))
    return set(available[: min(meme_count, len(available))])


def _clamp_duration(duration: int) -> int:
    return max(45, min(55, int(duration)))


def _coerce_meme(data: Any) -> MemeMoment:
    if not isinstance(data, dict):
        data = {}
    return MemeMoment(
        time_start=float(data.get("time_start", data.get("start", 0)) or 0),
        time_end=float(data.get("time_end", data.get("end", 0)) or 0),
        meme_type=str(data.get("meme_type") or "caption_pop"),
        caption=str(data.get("caption") or ""),
        visual_style=str(data.get("visual_style") or "quick pop"),
        reason=str(data.get("reason") or ""),
    )


def _first_hook_template(script: dict) -> str:
    hooks = script.get("hooks", []) or []
    for hook in hooks:
        if hook.get("template"):
            return str(hook["template"])
    return ""


def _build_meme_items(raw: dict, script_beats: list[dict], profile: dict) -> list[dict]:
    moments = raw.get("meme_moments") or []
    editing = get_editing_config(profile)
    low, high = editing.get("meme_beats", [1, 3])
    beat_target = max(2, len(script_beats) // 4)
    target = max(low, min(high, max(len(moments), beat_target)))
    items: list[dict] = []
    for index, moment in enumerate(moments[:target]):
        if not isinstance(moment, dict):
            continue
        beat = script_beats[index % len(script_beats)] if script_beats else {}
        items.append({
            "type": "meme",
            "query": moment.get("query") or moment.get("caption") or beat.get("script_text", "reaction"),
            "template_hint": moment.get("template_hint") or moment.get("meme_type") or "surprised",
            "meme_text_top": moment.get("meme_text_top") or "WAIT WHAT",
            "meme_text_bottom": moment.get("meme_text_bottom") or "IT GETS WORSE",
            "time_start": moment.get("time_start", moment.get("start", 0)),
            "time_end": moment.get("time_end", moment.get("end", 0)),
        })
    while len(items) < target and script_beats:
        beat = script_beats[len(items) % len(script_beats)]
        items.append({
            "type": "meme",
            "query": beat.get("script_text", "reaction"),
            "template_hint": "surprised",
            "meme_text_top": "WAIT WHAT",
            "meme_text_bottom": "IT GETS WORSE",
        })
    return items


def _beat_duration(beat: Any, total_duration: int, beat_count: int, index: int) -> float:
    if isinstance(beat, dict):
        start = beat.get("start")
        end = beat.get("end")
        if start is not None and end is not None:
            return max(1.0, float(end) - float(start))
    return total_duration / max(1, beat_count or index + 1)


def _enforce_narration_budget(narration: str, cta: str, duration_seconds: float) -> str:
    """Hard-cap narration at 132 WPM while preferring complete sentences."""
    max_total_words = max(1, int(duration_seconds * 2.2))
    narration_budget = max(1, max_total_words - len(cta.split()))
    words = narration.split()
    if len(words) <= narration_budget:
        return narration.strip()

    candidate = words[:narration_budget]
    sentence_end = next(
        (
            index
            for index in range(len(candidate) - 1, max(-1, len(candidate) // 2 - 1), -1)
            if candidate[index].endswith((".", "!", "?"))
        ),
        None,
    )
    if sentence_end is not None:
        candidate = candidate[: sentence_end + 1]
    elif candidate:
        candidate[-1] = candidate[-1].rstrip(",;:") + "."
    return " ".join(candidate)


def _bundle_to_dict(bundle: ResearchBundle) -> dict[str, Any]:
    return {
        "topic": bundle.topic,
        "niche": bundle.niche,
        "notes": [note.__dict__ for note in bundle.notes],
    }


def _format_short_script_markdown(
    short_script: ShortScript,
    beats: list[Any],
    profile: NicheProfile,
) -> str:
    lines = [
        f"# {short_script.title}",
        "",
        f"Niche: {profile.name}",
        f"Target duration: {short_script.total_duration_seconds:.0f}s",
        "",
        "## Hook",
        "",
        short_script.hook_question,
        "",
        "## Narration",
        "",
        short_script.condensed_narration,
        "",
        "## Beats",
        "",
    ]
    for index, beat in enumerate(beats or [], start=1):
        if isinstance(beat, dict):
            caption = beat.get("caption", "")
            visual = beat.get("visual", "")
        else:
            caption = str(beat)
            visual = ""
        lines.append(f"{index}. {caption} — {visual}".strip())
    lines.extend(["", "## CTA", "", short_script.cta_narration, ""])
    return "\n".join(lines)


def _build_scene_recipe_inputs(
    *,
    script_beats: list[dict[str, Any]],
    component_plan: dict[str, Any],
    beat_mode_plan: list[dict[str, Any]],
    project_id: str,
    topic: str,
    niche: str,
    visual_direction: dict[str, Any],
) -> list[SceneRecipeInput]:
    components_by_id = {
        str(item.get("id")): item for item in component_plan.get("components", [])
    }
    meme_beat_ids = {
        str(item.get("id")) for item in beat_mode_plan if item.get("mode") == "meme"
    }
    beats_by_id = visual_direction.get("beats_by_id", {}) if isinstance(visual_direction, dict) else {}
    total = len(script_beats)
    return [
        SceneRecipeInput(
            beat_id=str(beat.get("beat_id", f"beat_{index + 1:03d}")),
            beat_index=index,
            beat_count=total,
            topic=topic,
            niche=niche,
            narration=str(beat.get("script_text", "")),
            caption_text=str(beat.get("script_text", "")),
            visual_description=str(beat.get("visual_description", "")),
            visual_elements=list(beat.get("entities", [])),
            component_type=str(
                (components_by_id.get(str(beat.get("beat_id"))) or {})
                .get("visual", {})
                .get("type", "concept_card")
            ),
            has_meme=str(beat.get("beat_id")) in meme_beat_ids,
            seriousness_score=_seriousness_score(project_id, topic, niche),
            body_type=str(beats_by_id.get(str(beat.get("beat_id")), {}).get("body_type", "body1")),
            head="M",
            emotion=str(beats_by_id.get(str(beat.get("beat_id")), {}).get("emotion", "content")),
            gesture=str(beats_by_id.get(str(beat.get("beat_id")), {}).get("gesture", "")),
            background_image=str(
                beats_by_id.get(str(beat.get("beat_id")), {}).get("background_image", "")
            ),
        )
        for index, beat in enumerate(script_beats)
    ]


def _seriousness_score(project_id: str, topic: str, niche: str) -> float:
    text = f"{project_id} {topic} {niche}".lower()
    serious_terms = (
        "war",
        "death",
        "disaster",
        "election",
        "violence",
        "crime",
        "disease",
        "politics",
    )
    return 0.9 if any(term in text for term in serious_terms) else 0.0


def _mock_short_payload(topic: str, duration: int) -> dict[str, Any]:
    return {
        "title": topic,
        "hook": f"Here is the fastest way to understand {topic}.",
        "narration": (
            f"{topic} sounds complicated, but the core idea is simple. "
            "Start with the pattern. Watch where it breaks. "
            "Then use that mistake to explain the real lesson."
        ),
        "beats": [
            {"caption": "Start with the pattern", "start": 0, "end": duration * 0.33, "visual": "pattern grid"},
            {"caption": "Watch where it breaks", "start": duration * 0.33, "end": duration * 0.66, "visual": "glitch stamp"},
            {"caption": "Reveal the real lesson", "start": duration * 0.66, "end": duration, "visual": "clean reveal"},
        ],
        "cta": "Follow for the full breakdown.",
        "meme_moments": [
            {
                "time_start": duration * 0.36,
                "time_end": duration * 0.44,
                "meme_type": "reaction_label",
                "caption": "wait, that broke?",
                "visual_style": "quick zoom and shake",
                "reason": "Pattern-break moment keeps retention high.",
            }
        ],
    }
